### ISSUE TITLE
请教一下这个内核按照 README.md 文档构建完之后，如何使用如何运行

### ISSUE THREAD

**Issue by phial3** [hanbings/canicula#1]

**Comment by hanbings** [comment]
您好，感谢您对这个项目的关注。

关于使用 qemu 运行内核的说明在：https://github.com/hanbings/canicula/blob/main/docs/dev-environment.md
此外这个项目是一个学习性的项目，在过去几个月进度比较慢，还没有完成内存管理、进程管理和文件系统等的功能。
但在近期会有这些功能的更新，如果有了进展再在这里提醒您可以吗？

再次感谢。

**Comment by phial3** [comment]
> 您好，感谢您对这个项目的关注。
> 
> 关于使用 qemu 运行内核的说明在：https://github.com/hanbings/canicula/blob/main/docs/dev-environment.md 此外这个项目是一个学习性的项目，在过去几个月进度比较慢，还没有完成内存管理、进程管理和文件系统等的功能。 但在近期会有这些功能的更新，如果有了进展再在这里提醒您可以吗？
> 
> 再次感谢。

文档我看了，在macOS M2上构建 aarch64 架构的内核，运行qemu就卡死了想请教一下
```bash
qemu-system-aarch64 \
    -machine virt \
    -nographic \
    -bios bootloader/rustsbi-qemu.bin \
    -device loader,file=target/aarch64-unknown-uefi/debug/canicula-efi.efi
```

**Comment by hanbings** [comment]
很抱歉这么久才回复您，AArch 64 内核尚未完成引导部分内容，暂时也还没有实际作用的内核代码，因此还无法使用 qemu 启动它。
感谢您的关注。
